apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: azure-playground
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: azure-playground
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./charts/azure-playground
      sourceRef:
        kind: GitRepository
        name: azure-playground
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: azure-playground-values
      valuesKey: values.yaml
  values:
    frontend:
      replicaCount: 1
      service:
        type: LoadBalancer
        port: 80
    agentService:
      replicaCount: 1
      service:
        type: ClusterIP
        port: 5001
