apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azure-playground.name" . }}-llm-service-config
  labels:
    {{- include "azure-playground.llmService.labels" . | nindent 4 }}
data:
  AZURE_OPENAI_ENDPOINT: {{ required "llmService.azureOpenAI.endpoint is required" .Values.llmService.azureOpenAI.endpoint | quote }}
