apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azure-playground.name" . }}-agent-service-config
  labels:
    {{- include "azure-playground.agentService.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ required "environment is required" .Values.environment | quote }}
