apiVersion: v1
kind: Service
metadata:
  name: {{ include "azure-playground.name" . }}-llm-service
  labels:
    {{- include "azure-playground.llmService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.llmService.service.type }}
  selector:
    {{- include "azure-playground.llmService.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.llmService.service.port }}
      targetPort: http
