apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "azure-playground.name" . }}-kv
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azure-playground.agentService.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ required "keyVault.kubeletClientId is required" .Values.keyVault.kubeletClientId | quote }}
    keyvaultName: {{ required "keyVault.name is required" .Values.keyVault.name | quote }}
    tenantId: {{ required "keyVault.tenantId is required" .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: azure-openai-endpoint
          objectType: secret
        - |
          objectName: news-api-key
          objectType: secret
  secretObjects:
    - secretName: {{ include "azure-playground.name" . }}-agent-service-secrets
      type: Opaque
      data:
        - objectName: azure-openai-endpoint
          key: AZURE_OPENAI_ENDPOINT
        - objectName: news-api-key
          key: NEWS_API_KEY
