# ConfigMaps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-playground-llm-service-config
data:
  AZURE_OPENAI_ENDPOINT: <AZURE_OPENAI_ENDPOINT>

# Deployments
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-playground-frontend
  labels:
    app: azure-playground-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-playground-frontend
  template:
    metadata:
      labels:
        app: azure-playground-frontend
    spec:
      containers:
      - name: azure-playground-frontend
        image: <AZURE_PLAYGROUND_FRONTEND_IMAGE>
        ports:
        - containerPort: 80
        env:
        - name: VITE_LLM_SERVICE_URL
          value: "http://azure-playground-llm-service:5001"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-playground-llm-service
  labels:
    app: azure-playground-llm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-playground-llm-service
  template:
    metadata:
      labels:
        app: azure-playground-llm-service
    spec:
      containers:
      - name: azure-playground-llm-service
        image: <AZURE_PLAYGROUND_LLM_SERVICE_IMAGE>
        ports:
        - containerPort: 5001
        env:
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: azure-playground-llm-service-config
              key: AZURE_OPENAI_ENDPOINT

# Services
---
apiVersion: v1
kind: Service
metadata:
  name: azure-playground-frontend
spec:
  type: LoadBalancer
  selector:
    app: azure-playground-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http

---
apiVersion: v1
kind: Service
metadata:
  name: azure-playground-llm-service
spec:
  type: ClusterIP
  selector:
    app: azure-playground-llm-service
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    name: http