apiVersion: v1
kind: ConfigMap
metadata:
  name: arXiv-ai-agent-configmap
data:
  TEMPERATURE: ""
  AZURE_OPENAI_BASE: ""
  AZURE_OPENAI_KEY: ""
  AZURE_OPENAI_MODEL: model-router
  AZURE_OPENAI_DEPLOYMENT: model-router