apiVersion: v1
kind: Service
metadata:
  name: azure-playground
spec:
  type: LoadBalancer
  selector:
    app: azure-playground
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      name: http